apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api-service
  labels:
    app: url-shortener
  annotations:
    kubernetes.io/elb.id: ELB_ID_REPLACE
    kubernetes.io/elb.class: performance
spec:
  selector:
    app: url-shortener  # This should match the label on your deployment
  ports:
    - protocol: TCP
      port: 80  # The port Kubernetes will expose internally
      targetPort: 8080  # The port your container is listening on
      nodePort: 30080  
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-api
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: swr.tr-west-1.myhuaweicloud.com/exci_case/url-shortener:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DSN
              value: "root:Bugrahanexzi1234.@tcp(MYSQL_DB_IP:3306)/" # Replace with the actual DSN for MySQL
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
      imagePullSecrets:
        - name: default-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: url-shortener-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shortener-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

