name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}

      - name: Build Docker image
        working-directory: url-shortener
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/exci_case/url-shortener:latest .
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/exci_case/url-shortener:latest

      - name: Pull redis image
        run: docker pull redis:alpine

      - name: tag redis image
        run: docker tag redis:alpine ${{ secrets.DOCKER_REGISTRY }}/exci_case/redis:alpine

      - name: Push redis image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/exci_case/redis:alpine

      - name: trigger jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://101.44.38.124:8080"
          user: "admin"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "exzi_case"