name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: swr.tr-west-1.myhuaweicloud.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./url-shortener
          push: true
          tags: swr.tr-west-1.myhuaweicloud.com/exci_case/url-shortener:latest
          file: ./url-shortener/Dockerfile
