name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Plan Terraform Changes
      env:
        HUAWEICLOUD_ACCESS_KEY: ${{ secrets.HUAWEICLOUD_ACCESS_KEY }}
        HUAWEICLOUD_SECRET_KEY: ${{ secrets.HUAWEICLOUD_SECRET_KEY }}
      run: 
        terraform plan -var "huaweicloud_access_key=$HUAWEICLOUD_ACCESS_KEY" -var "huaweicloud_secret_key=$HUAWEICLOUD_SECRET_KEY"
      working-directory: terraform

    - name: Apply Terraform Changes
      env:
        HUAWEICLOUD_ACCESS_KEY: ${{ secrets.HUAWEICLOUD_ACCESS_KEY }}
        HUAWEICLOUD_SECRET_KEY: ${{ secrets.HUAWEICLOUD_SECRET_KEY }}
      run: 
        terraform apply -auto-approve -var "huaweicloud_access_key=$HUAWEICLOUD_ACCESS_KEY" -var "huaweicloud_secret_key=$HUAWEICLOUD_SECRET_KEY"
      working-directory: terraform

